name: Build Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/reusable-deploy-workflow.yml
    with:
      env_name: 'dev'
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}


  

