name: Build Master Branch

on:
  push:
    branches:
      - master

jobs:
  cdk:
    uses: ./.github/workflows/reusable-deploy-workflow.yml
    with:
      env_name: 'prod'
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}


  

