################################################################################
# Deployment Pipeline
#
# This workflow is called from the environment-specific worflows.
################################################################################


on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
        description: Name of the environment to deploy e.g. 'dev'.  
    secrets:
      NODE_AUTH_TOKEN:
        required: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      
      - run: npm build

      - name: Unit Tests
        run: npm test 
